AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Customer Satisfaction Prediction API - Serverless MLOps Project

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.12
    Environment:
      Variables:
        MODEL_BUCKET: !Ref ModelBucket
        MODEL_KEY: models/production/model
        MODEL_VERSION: v1.0

Resources:
  # S3 Bucket for model artifacts
  ModelBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-models-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # Lambda function for predictions
  PredictionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref ModelBucket
      Events:
        PredictAPI:
          Type: Api
          Properties:
            Path: /predict
            Method: post
            RestApiId: !Ref ApiGateway
        PredictOptions:
          Type: Api
          Properties:
            Path: /predict
            Method: options
            RestApiId: !Ref ApiGateway

  # Health check function
  HealthCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_function.health_check
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        HealthAPI:
          Type: Api
          Properties:
            Path: /health
            Method: get
            RestApiId: !Ref ApiGateway

  # API Gateway
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'POST, GET, OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
        AllowOrigin: "'*'"
      DefinitionBody:
        swagger: '2.0'
        info:
          title: Customer Satisfaction Prediction API
          version: '1.0'
        paths:
          /predict:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PredictionFunction.Arn}/invocations'
              responses:
                '200':
                  description: Successful prediction
            options:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PredictionFunction.Arn}/invocations'
              responses:
                '200':
                  description: CORS support
          /health:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HealthCheckFunction.Arn}/invocations'
              responses:
                '200':
                  description: Health check

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod"

  PredictionEndpoint:
    Description: "Prediction endpoint URL"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/predict"

  HealthCheckEndpoint:
    Description: "Health check endpoint URL"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/health"

  ModelBucketName:
    Description: "S3 bucket for model artifacts"
    Value: !Ref ModelBucket
